"""baseline: extensions + organizations + users

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-29

Establishes the database foundation:
  - required extensions (pg_trgm, btree_gist, citext; vector optionally)
  - the user_role ENUM
  - organizations + users (the org-scoping / auth foundation)

Hand-written (not autogenerated) so the extension and constraint DDL is fully
controlled. pgvector is created only when RV_ENABLE_PGVECTOR is set, since it is
an optional Phase-1 dependency (DECISIONS.md D-0005).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from app.config import get_settings
from sqlalchemy.dialects import postgresql

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

USER_ROLE = postgresql.ENUM(
    "owner", "ops_manager", "sales", "accounts", "readonly",
    name="user_role",
    create_type=False,
)


def upgrade() -> None:
    # --- extensions ---------------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    if get_settings().rv_enable_pgvector:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # --- enum types ---------------------------------------------------------
    USER_ROLE.create(op.get_bind(), checkfirst=True)

    # --- organizations ------------------------------------------------------
    op.create_table(
        "organizations",
        sa.Column(
            "id", postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"), nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", postgresql.CITEXT(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_organizations"),
        sa.UniqueConstraint("slug", name="uq_organizations_slug"),
    )

    # --- users --------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column(
            "id", postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"), nullable=False,
        ),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("role", USER_ROLE, server_default="readonly", nullable=False),
        sa.Column("is_active", sa.Boolean(),
                  server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"],
            name="fk_users_org_id_organizations",
        ),
        sa.UniqueConstraint("org_id", "email", name="uq_users_org_id"),
    )


def downgrade() -> None:
    op.drop_table("users")
    op.drop_table("organizations")
    USER_ROLE.drop(op.get_bind(), checkfirst=True)
    # Extensions are intentionally left installed on downgrade — dropping shared
    # extensions can break other objects and they are harmless if unused.
