"""canonical schema

Revision ID: 7e604edc5cfc
Revises: 0001_baseline
Create Date: 2026-07-29

Canonical supplier + rate core (Part 2 §4.1–4.2): destinations, suppliers,
isolated supplier_commercials, supplier_contacts, room_types, rates (with the
no-overlap exclusion constraint), transport_rates, activity_rates, guide_rates,
misc_costs. Every table is org-scoped; every rate table carries provenance.

Autogenerated, then hand-adjusted: (1) the new ENUM types are created once up
front with create_type=False on the columns, so a type used by several tables
(e.g. rate_lifecycle) is not re-created; (2) the enum types are dropped on
downgrade; (3) no spurious ALTER on the existing users table.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from app.models import enums as e
from sqlalchemy.dialects import postgresql

revision: str = "7e604edc5cfc"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _enum(enum_cls: type, name: str) -> postgresql.ENUM:
    """PG ENUM built from the Python enum's values; created explicitly, so
    create_type=False keeps op.create_table from re-emitting CREATE TYPE."""
    return postgresql.ENUM(*[m.value for m in enum_cls], name=name, create_type=False)


supplier_kind = _enum(e.SupplierKind, "supplier_kind")
meal_plan = _enum(e.MealPlan, "meal_plan")
occupancy = _enum(e.Occupancy, "occupancy")
tax_basis = _enum(e.TaxBasis, "tax_basis")
transport_basis = _enum(e.TransportBasis, "transport_basis")
pax_class = _enum(e.PaxClass, "pax_class")
allocation_basis = _enum(e.AllocationBasis, "allocation_basis")
rate_lifecycle = _enum(e.RateLifecycle, "rate_lifecycle")

NEW_ENUMS = [
    supplier_kind, meal_plan, occupancy, tax_basis,
    transport_basis, pax_class, allocation_basis, rate_lifecycle,
]


def upgrade() -> None:
    bind = op.get_bind()
    for en in NEW_ENUMS:
        en.create(bind, checkfirst=True)

    op.create_table(
        "destinations",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column("lat", sa.Numeric(9, 6), nullable=True),
        sa.Column("lng", sa.Numeric(9, 6), nullable=True),
        sa.Column("aliases", postgresql.ARRAY(sa.Text()),
                  server_default="{}", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"],
                                name="fk_destinations_org_id_organizations"),
        sa.PrimaryKeyConstraint("id", name="pk_destinations"),
        sa.UniqueConstraint("org_id", "name", "state", "country",
                            name="uq_destinations_org_id"),
    )
    op.create_index("ix_destinations_org_id", "destinations", ["org_id"])

    op.create_table(
        "suppliers",
        sa.Column("kind", supplier_kind, nullable=False),
        sa.Column("legal_name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("destination_id", sa.UUID(), nullable=True),
        sa.Column("gstin", sa.Text(), nullable=True),
        sa.Column("pan", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("property_type", sa.Text(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.Text()),
                  server_default="{}", nullable=False),
        sa.Column("status", sa.Text(), server_default="prospect", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["destination_id"], ["destinations.id"],
                                name="fk_suppliers_destination_id_destinations"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"],
                                name="fk_suppliers_org_id_organizations"),
        sa.PrimaryKeyConstraint("id", name="pk_suppliers"),
    )
    op.create_index("ix_suppliers_org_id", "suppliers", ["org_id"])

    op.create_table(
        "supplier_commercials",
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("commission_pct", sa.Numeric(5, 2), nullable=True),
        sa.Column("margin_pct", sa.Numeric(5, 2), nullable=True),
        sa.Column("commission_notes", sa.Text(), nullable=True),
        sa.Column("criteria_of_shortlisting", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"],
                                name="fk_supplier_commercials_org_id_organizations"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"],
                                name="fk_supplier_commercials_supplier_id_suppliers"),
        sa.PrimaryKeyConstraint("id", name="pk_supplier_commercials"),
        sa.UniqueConstraint("supplier_id",
                            name="uq_supplier_commercials_supplier_id"),
    )
    op.create_index("ix_supplier_commercials_org_id", "supplier_commercials",
                    ["org_id"])

    op.create_table(
        "supplier_contacts",
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("person_name", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("phone_e164", sa.Text(), nullable=True),
        sa.Column("phone_raw", sa.Text(), nullable=True),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("preferred_channel", sa.Text(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("unusable_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"],
                                name="fk_supplier_contacts_org_id_organizations"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"],
                                name="fk_supplier_contacts_supplier_id_suppliers"),
        sa.PrimaryKeyConstraint("id", name="pk_supplier_contacts"),
    )
    op.create_index("ix_supplier_contacts_org_id", "supplier_contacts", ["org_id"])

    op.create_table(
        "room_types",
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("max_adults", sa.Integer(), server_default="2", nullable=False),
        sa.Column("max_children", sa.Integer(), server_default="1", nullable=False),
        sa.Column("extra_bed_allowed", sa.Boolean(),
                  server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"],
                                name="fk_room_types_org_id_organizations"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"],
                                name="fk_room_types_supplier_id_suppliers"),
        sa.PrimaryKeyConstraint("id", name="pk_room_types"),
    )
    op.create_index("ix_room_types_org_id", "room_types", ["org_id"])

    op.create_table(
        "rates",
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("room_type_id", sa.UUID(), nullable=True),
        sa.Column("meal_plan", meal_plan, nullable=False),
        sa.Column("occupancy", occupancy, nullable=False),
        sa.Column("amount", sa.Numeric(14, 2), nullable=False),
        sa.Column("currency", sa.CHAR(3), server_default="INR", nullable=False),
        sa.Column("tax_basis", tax_basis,
                  server_default="gross_of_tax", nullable=False),
        sa.Column("tax_pct", sa.Numeric(5, 2), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=False),
        sa.Column("season_label", sa.Text(), nullable=True),
        sa.Column("min_nights", sa.Integer(), server_default="1", nullable=False),
        sa.Column("blackout_dates", postgresql.ARRAY(postgresql.DATERANGE()),
                  nullable=True),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("raw_source_text", sa.Text(), nullable=True),
        sa.Column("extraction_confidence", sa.Numeric(3, 2), nullable=True),
        sa.Column("lifecycle", rate_lifecycle,
                  server_default="candidate", nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount >= 0", name="ck_rates_amount_non_negative"),
        sa.CheckConstraint("valid_to >= valid_from", name="ck_rates_valid_dates"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"],
                                name="fk_rates_org_id_organizations"),
        sa.ForeignKeyConstraint(["room_type_id"], ["room_types.id"],
                                name="fk_rates_room_type_id_room_types"),
        sa.ForeignKeyConstraint(["supersedes_id"], ["rates.id"],
                                name="fk_rates_supersedes_id_rates"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"],
                                name="fk_rates_supplier_id_suppliers"),
        sa.ForeignKeyConstraint(["verified_by"], ["users.id"],
                                name="fk_rates_verified_by_users"),
        sa.PrimaryKeyConstraint("id", name="pk_rates"),
    )
    op.create_index("ix_rates_lookup", "rates",
                    ["supplier_id", "meal_plan", "occupancy",
                     "valid_from", "valid_to"])
    op.create_index("ix_rates_org_id", "rates", ["org_id"])
    # No-overlap exclusion (needs btree_gist). Raw SQL for full control.
    op.execute(
        "ALTER TABLE rates ADD CONSTRAINT rates_no_overlap "
        "EXCLUDE USING gist ("
        "  supplier_id WITH =, room_type_id WITH =, "
        "  meal_plan WITH =, occupancy WITH =, "
        "  daterange(valid_from, valid_to, '[]') WITH &&"
        ") WHERE (deleted_at IS NULL)"
    )

    op.create_table(
        "transport_rates",
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_class", sa.Text(), nullable=False),
        sa.Column("vehicle_model", sa.Text(), nullable=True),
        sa.Column("seats", sa.Integer(), nullable=True),
        sa.Column("basis", transport_basis, nullable=False),
        sa.Column("amount", sa.Numeric(14, 2), nullable=False),
        sa.Column("origin_destination_id", sa.UUID(), nullable=True),
        sa.Column("route_to_destination_id", sa.UUID(), nullable=True),
        sa.Column("includes_driver_da", sa.Boolean(),
                  server_default="false", nullable=False),
        sa.Column("includes_fuel", sa.Boolean(),
                  server_default="true", nullable=False),
        sa.Column("includes_tolls", sa.Boolean(),
                  server_default="false", nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("raw_source_text", sa.Text(), nullable=True),
        sa.Column("extraction_confidence", sa.Numeric(3, 2), nullable=True),
        sa.Column("lifecycle", rate_lifecycle,
                  server_default="candidate", nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount >= 0",
                           name="ck_transport_rates_amount_non_negative"),
        sa.CheckConstraint("valid_to >= valid_from",
                           name="ck_transport_rates_valid_dates"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"],
                                name="fk_transport_rates_org_id_organizations"),
        sa.ForeignKeyConstraint(
            ["origin_destination_id"], ["destinations.id"],
            name="fk_transport_rates_origin_destination_id_destinations"),
        sa.ForeignKeyConstraint(
            ["route_to_destination_id"], ["destinations.id"],
            name="fk_transport_rates_route_to_destination_id_destinations"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"],
                                name="fk_transport_rates_supplier_id_suppliers"),
        sa.ForeignKeyConstraint(["verified_by"], ["users.id"],
                                name="fk_transport_rates_verified_by_users"),
        sa.PrimaryKeyConstraint("id", name="pk_transport_rates"),
    )
    op.create_index("ix_transport_rates_org_id", "transport_rates", ["org_id"])

    op.create_table(
        "activity_rates",
        sa.Column("destination_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("pax_class", pax_class, nullable=False),
        sa.Column("price_per_pax", sa.Numeric(14, 2), nullable=False),
        sa.Column("child_price", sa.Numeric(14, 2), nullable=True),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("raw_source_text", sa.Text(), nullable=True),
        sa.Column("extraction_confidence", sa.Numeric(3, 2), nullable=True),
        sa.Column("lifecycle", rate_lifecycle,
                  server_default="candidate", nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("price_per_pax >= 0",
                           name="ck_activity_rates_price_non_negative"),
        sa.CheckConstraint("valid_to >= valid_from",
                           name="ck_activity_rates_valid_dates"),
        sa.ForeignKeyConstraint(["destination_id"], ["destinations.id"],
                                name="fk_activity_rates_destination_id_destinations"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"],
                                name="fk_activity_rates_org_id_organizations"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"],
                                name="fk_activity_rates_supplier_id_suppliers"),
        sa.ForeignKeyConstraint(["verified_by"], ["users.id"],
                                name="fk_activity_rates_verified_by_users"),
        sa.PrimaryKeyConstraint("id", name="pk_activity_rates"),
    )
    op.create_index("ix_activity_rates_org_id", "activity_rates", ["org_id"])

    op.create_table(
        "guide_rates",
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("destination_id", sa.UUID(), nullable=True),
        sa.Column("languages", postgresql.ARRAY(sa.Text()),
                  server_default="{}", nullable=False),
        sa.Column("per_day", sa.Numeric(14, 2), nullable=True),
        sa.Column("per_half_day", sa.Numeric(14, 2), nullable=True),
        sa.Column("specialisation", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("raw_source_text", sa.Text(), nullable=True),
        sa.Column("extraction_confidence", sa.Numeric(3, 2), nullable=True),
        sa.Column("lifecycle", rate_lifecycle,
                  server_default="candidate", nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("valid_to >= valid_from",
                           name="ck_guide_rates_valid_dates"),
        sa.ForeignKeyConstraint(["destination_id"], ["destinations.id"],
                                name="fk_guide_rates_destination_id_destinations"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"],
                                name="fk_guide_rates_org_id_organizations"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"],
                                name="fk_guide_rates_supplier_id_suppliers"),
        sa.ForeignKeyConstraint(["verified_by"], ["users.id"],
                                name="fk_guide_rates_verified_by_users"),
        sa.PrimaryKeyConstraint("id", name="pk_guide_rates"),
    )
    op.create_index("ix_guide_rates_org_id", "guide_rates", ["org_id"])

    op.create_table(
        "misc_costs",
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("destination_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(14, 2), nullable=True),
        sa.Column("currency", sa.CHAR(3), server_default="INR", nullable=False),
        sa.Column("allocation", allocation_basis,
                  server_default="all_pax", nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("raw_source_text", sa.Text(), nullable=True),
        sa.Column("extraction_confidence", sa.Numeric(3, 2), nullable=True),
        sa.Column("lifecycle", rate_lifecycle,
                  server_default="candidate", nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount IS NULL OR amount >= 0",
                           name="ck_misc_costs_amount_non_negative"),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from",
            name="ck_misc_costs_valid_dates"),
        sa.ForeignKeyConstraint(["destination_id"], ["destinations.id"],
                                name="fk_misc_costs_destination_id_destinations"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"],
                                name="fk_misc_costs_org_id_organizations"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"],
                                name="fk_misc_costs_supplier_id_suppliers"),
        sa.ForeignKeyConstraint(["verified_by"], ["users.id"],
                                name="fk_misc_costs_verified_by_users"),
        sa.PrimaryKeyConstraint("id", name="pk_misc_costs"),
    )
    op.create_index("ix_misc_costs_org_id", "misc_costs", ["org_id"])


def downgrade() -> None:
    op.drop_table("misc_costs")
    op.drop_table("guide_rates")
    op.drop_table("activity_rates")
    op.drop_table("transport_rates")
    op.drop_table("rates")
    op.drop_table("room_types")
    op.drop_table("supplier_contacts")
    op.drop_table("supplier_commercials")
    op.drop_table("suppliers")
    op.drop_table("destinations")

    bind = op.get_bind()
    for en in NEW_ENUMS:
        en.drop(bind, checkfirst=True)
